spring:
  application:
    name: jobtracker

  datasource:
    url: jdbc:mysql://localhost:3306/jobtracker?useSSL=false&serverTimezone=UTC
    username: root
    password: yourpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true